# cluster specific values
cluster:
  # specify cluster name
  name: template-rke2

  # specify cluster labels
  labels: {}

  # specify cluster annotations
  annotations: {}

# specify cloud credential secret name, do not need to be provided if using custom driver
cloudCredentialSecretName: ""

# specify cloud provider, options are amazonec2, digitalocean, azure, vsphere or custom
cloudprovider: "amazonec2"

kubernetesVersion: "v1.26.7+rke2r1"

# general RKE options
rke:
  # enable local auth endpoint
  localClusterAuthEndpoint:
    enabled: false
  # specify fqdn of local access endpoint
  # fqdn: foo.bar.example
  # specify cacert of local access endpoint
  # caCerts: ""

# specify user principal ids to be assiged as cluster members
# clusterMembers:
# - principalName: "local://u-z8zl5"
#   roleTemplateName: "cluster-member"

# enable monitoring
monitoring:
  enabled: false
  # specify which version to install, can be semver range. If version is empty or is semver range, it will pick up the latest version.
  # version: ""
  # specify cutsom values set
  # values:
  #   foo: bar
#Default nodepools
nodepools:
  '0':
    name: nodepool1
    quantity: 3
    etcd: true
    worker: true
    controlplane: true
    ami: ami-0e6577a75723c81f8
    backups: false
    ipv6: false
    monitoring: false
    privateNetworking: false
    region: us-east-2
    userdata: null
    sshPort: 22
    sshUser: ubuntu
    zone: a
    instanceType: t3a.medium
    rootSize: '"100"'
